# html lang
language: zh

# main menu navigation
menu:
    # Home: /
    Archives: archives
    About: about
    Tool: tool
    404: 404
    Link: link

# display in the home page 
home_title: WELCOME
# display in the head right
header_right: It's more tiring to stop
# display after the article when copyRight of the page is true 
article_txt: 转载请注明来源，欢迎对文章中的引用来源进行考证，欢迎指出任何有错误或不够清晰的表达

social:
    Home:
        title: Home
        url: /archives
         # if there haven't icon you need  then you can use the image and put it on the source/images/icon
         # img: /images/icon
        icon: iconHome
        index: true # whether to display in the index page
        sidebar: true # whether to display in the left side
    RSS:
        title: RSS 源订阅
        url: /atom.xml
        icon: iconsubscribe-1-copy
        index: true
        sidebar: true
    E-Mail:
        title: E-Mail
        url: mailto:tongt0232@gmail.com
        icon: iconweibiaoti554
        index: true
        sidebar: true
    GitHub:
        title: GitHub
        url: https://github.com/tong-h
        icon: iconGitHub
        index: true
        sidebar: true
    简书:
        title: 简书 
        url: https://www.jianshu.com/u/20de04cc53de
        img: /images/jianicon
        index: true
        sidebar: true

Gitalk:
    enable: true # if you want gitalk
    id: ''
    owner: Tong-H 
    repo: Tong-H.github.io # repo of issue
    admin: Tong-H # you and your partner, split by the comma
    client_id: 5658f62c9837c979f96f # Client ID
    client_secret: 36813d127f4f0918cd30231a403e09d81015e014 # Client secret
    distractionFreeMode: false
